import 'package:flutter/material.dart';
import '../pdf engine/pdf_engine.dart';
import '../models/report_model.dart';

class ContentInputScreen extends StatefulWidget {
  @override
  _ContentInputScreenState createState() => _ContentInputScreenState();
}

class _ContentInputScreenState extends State<ContentInputScreen> {
  // Sirf content ke liye controller
  final TextEditingController _contentController = TextEditingController();
  final PdfEngine _pdfEngine = PdfEngine();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Medical Report Editor"),
        backgroundColor: Colors.blueAccent,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              "Enter Report Findings:",
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 10),

            // Bada text box jahan aap content likhenge
            Expanded(
              child: TextFormField(
                controller: _contentController,
                maxLines: null, // Jitna bada content, utni lines
                expands: true,
                textAlignVertical: TextAlignVertical.top,
                decoration: InputDecoration(
                  hintText: "Example: Patient shows signs of minor mouth ulcers on the lower lip. No serious infection detected...",
                  border: OutlineInputBorder(),
                  focusedBorder: OutlineInputBorder(
                    borderSide: BorderSide(color: Colors.blueAccent, width: 2),
                  ),
                ),
              ),
            ),

            SizedBox(height: 20),

            // Button jo engine ko call karega
            SizedBox(
              width: double.infinity,
              height: 50,
              child: ElevatedButton.icon(
                onPressed: () async {
                  if (_contentController.text.isEmpty) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(content: Text("Please enter some content!")),
                    );
                    return;
                  }

                  // Default data + aapka likha hua content
                  final report = ReportModel(
                    title: "Mouth Ulcer Analysis Report",
                    description: _contentController.text, // Aapka input yahan ja raha hai
                    parameters: {
                      "Scan Date": DateTime.now().toString().split(' ')[0],
                      "Report Status": "Final",
                      "Generated By": "AI Engine v1.0",
                    },
                  );

                  await _pdfEngine.generateReport(report);
                },
                icon: Icon(Icons.picture_as_pdf),
                label: Text("GENERATE PROFESSIONAL PDF"),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.blueAccent,
                  foregroundColor: Colors.white,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}